/* 
	APÓS DEFINIR ONDE FICARÃO AS FK, AGORA PODE FAZER
	A MODELAGEM FÍSICA
 */
 
 CREATE TABLE CLIENTE(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(20) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF CHAR(11) UNIQUE
);

CREATE TABLE ENDERECO(
	ID_ENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	FK_IDCLIENTE INT UNIQUE,-- FOI COLOCADO O UNIQUE POIS O RELACIONAMENTO É 1X1
	FOREIGN KEY(FK_IDCLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE TELEFONE(
	ID_TELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	FK_IDCLIENTE INT,
	FOREIGN KEY(FK_IDCLIENTE)
	REFERENCES CLIENTE(ID_CLIENTE)
);
