/* PRIMEIRA FORMA NORMAL */

/* 
1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

VETORIZADO: POSSUI A MESMA NATUREZA
EX: CARROS -> [UNO, CIVIC, KA, FIESTA]

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA
QUANDO O CAMPO FOR DIVISÍVEL

MULTIVALORADO: NÃO POSSUI A MESMA NATUREZA
EX: ENDEREÇO -> [ESTADO, CIDADE, RUA, CEP]

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE
IDENTIFIQUE TODO O REGISTRO COMO SENDO ÚNICO

PRIMARY KEY: CHAVE ARTIFICIAL

 */