/* 

	FOREIGN KEY: DEPENDE DA REGRA DE NEGÓCIO
	
	OBS: TUDO DEPENDE DA CARDINALIDADE
	
	1) 1X1 -> A FK FICA NA TABELA MAIS FRACA
		- DEPENDE DA REGRA DE NEGÓCIO
		- NESSE EXEMPLO O QUE É MAIS "IMPORTANTE": 
			- CLIENTE OU ENDEREÇO? (R: CLIENTE)
	2) 1XN -> A FK SEMPRE FICARÁ NA "N"
		- NESSE CASO FICARÁ NA TABELA "TELEFONE"

 */