/* SELECT --> PROJEÇÃO */
/* FROM --> ORIGEM */
/* WHERE --> SELEÇÃO (FILTRO) */
/* INNER JOIN --> JUNÇÃO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
	INNER JOIN TELEFONE
	ON ID_CLIENTE = FK_IDCLIENTE
WHERE SEXO = 'F';