/*--- Modelagem Básica---*/

/* Processos de modelagem */
/* 
	FASE 01 --> MODELAGEM CONCEITUAL
		- É UM RASCUNHO DOS PRINCIPAIS REQUISITOS DO SISTEMA
		- FEITA PELO AD ADM DE DADOS
	FASE 02 --> MODELAGEM LÓGICA
		- FAZER DIAGRAMAÇÃO DO MODELO CONCEITUAL
		- FEITO EM QUALQUER PROGRAMA DE MODELAGEM
		- FEITO PELO AD ADM DE DADOS
	FASE 03 --> MODELAGEM FÍSICA
		- SCRIPTS DE BANCO
		- FEITO NA LINGUAGEM SQL
		- FEITO PELO DBA OU AD
*/

/* --- FASE 01 - MODELAGEM CONCEITUAL ---

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

*/

/* --- FASE 02 --> MODELAGEM LÓGICA ---

FEITA NO PROGRAMA brModel.

*/

/* --- FASE 03 -->  MODELAGEM FÍSICA ---*/

-- CRIANDO UM BANCO DE DADOS
CREATE DATABASE PROJETO;

-- CONECTANDO-SE AO BANCO
USE PROJETO;

-- CRIANDO UMA TABELA NO BANCO
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	CPF INT(11),
	ENDERECO VARCHAR(100),
	TELEFONE VARCHAR(30),
	EMAIL VARCHAR(30)
);

-- MOSTRAR TODAS AS TABELAS DO BANCO
SHOW TABLES;

-- DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA
DESC CLIENTE;