/* PERFORMANCE COM OPERADORES LÓGICOS */

-- CONTANDO REGISTROS DE UMA TABELA
SELECT COUNT(*) AS 'CONTADOR'
 FROM cliente;
 
-- OPERADOR GROUP BY
/* 
	CONTA A QUANTIDADE DE REGISTRO DA TABELA
	CLIENTE, AGRUPO POR SEXO
 */
SELECT SEXO, COUNT(*) AS 'CONTADOR'
FROM cliente
GROUP BY SEXO;

-- PERFORMANCE
/* 
	SITUAÇÃO:
	- 70% MULHERES
	- 30% MORA NO BRASIL
*/
-- TRATANDO COM O 'OR'
/*
	NO 'OR' BASTA A PRIMEIRA SETENÇA SER VERDADEIRA.
	LOGO, COLOCA A QUE TEM MAIOR PROBABILIDADE PRIMEIRO,
	PORQUE DAI EVITA PERDER TEMPO COM A SEGUNDA SENTENÇA
	QUE VENHA FALSO.
*/
SELECT NOME, SEXO, ENDERECO
FROM cliente
WHERE
SEXO = 'F' OR (ENDERECO LIKE '%BRASIL');

-- TRATANDO COM O 'AND'
/*
	NO 'AND' A CONDIÇÃO SÓ É VERDADEIRA SE AS DUAS SETENÇAS
	FOREM VERDADEIRAS TAMBÉM.
	LOGO, COLOCA PRIMEIRO A QUE TEM MENOS PROBABILIDADE QUE
	DAI SÓ VAI VERIFICAR AS SITUAÇÕES QUE SATISFAZEM A PRIMEIRA
	SENTENÇA, POUPANDO TEMPO EM PERCORRER A SEGUNDA QUE MESMO
	DANDO VERDADEIRO NÃO SATISFARÁ A CONDIÇÃO.
*/
SELECT NOME, SEXO, ENDERECO
FROM cliente
WHERE
(ENDERECO LIKE '%BRASIL') AND SEXO = 'F';