/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO FROM cliente
WHERE EMAIL IS NULL;

/* FILTRANDO VALORES NÃO NULOS */

SELECT NOME, SEXO, ENDERECO FROM cliente
WHERE EMAIL IS NOT NULL;