/* SELECT É UM COMANDO DE PROJEÇÃO E JUNÇÃO */

SELECT NOW();

SELECT NOW() as DATA_HORA, 'NOÉ MARTINS' AS PROFESSOR;

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

-- PROJETAR O 'CLIENTE' AO INVÉS DE 'NOME'

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* MOTIVOS PARA NÃO UTILIZAR NO DIA A DIA DA EMPRESA */
-- GERAR GARGALOS DE PROCESSAMENTO, TEMPO E DE REDE.
-- INVALIDA A FUNÇÃO DO 'INDEX'