/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE
WHERE SEXO = 'M';

/* UTILIZANDO O LIKE */
-- '%' = É UM ELEMENTO CORINGA
-- 'BRASIL%' = BRASIL ESTÁ NO COMEÇO
-- '%BRASIL%' = BRASIL ESTÁ ENTRE A FRASE
-- 'BRASIL%' = BRASIL ESTÁ NO FINAL
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%BRASIL';